name: jupyter
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - tensorflow-cpu
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - altair
  - beautifulsoup4
  - bokeh
  - bottleneck
  - cloudpickle
  - cython
  - dask
  - dill
  - h5py
  - ipympl
  - ipywidgets
  - jupyterlab-git
  - jupyterlab-lsp
  - python-lsp-server
  - matplotlib-base
  - numba
  - numexpr
  - openpyxl
  - pandas
  - patsy
  - protobuf
  - pytables
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - sqlalchemy
  - statsmodels
  - sympy
  - widgetsnbextension
  - xlrd
  - r-base
  - r-caret
  - r-crayon
  - r-devtools
  - r-e1071
  - r-forecast
  - r-hexbin
  - r-htmltools
  - r-htmlwidgets
  - r-irkernel
  - r-nycflights13
  - r-randomforest
  - r-rcurl
  - r-rmarkdown
  - r-rodbc
  - r-rsqlite
  - r-shiny
  - r-tidymodels
  - r-tidyverse
  - rpy2
  - unixodbc
