name: jupyter
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - tensorflow-cpu
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - altair
  - beautifulsoup4
  - bokeh
  - bottleneck
  - cloudpickle
  - cython
  - cytoolz
  - dask
  - dill
  - h5py
  - ipympl
  - ipywidgets
  - jupyterlab-git
  - jupyterlab-lsp
  - python-lsp-server
  - matplotlib-base
  - numba
  - numexpr
  - openpyxl
  - pandas
  - patsy
  - protobuf
  - pytables
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - sqlalchemy
  - statsmodels
  - sympy
  - widgetsnbextension
  - xlrd
